_G.main_menu_OnKeyboard = _G.ui_main_menu.main_menu.OnKeyboard
_G.ui_main_menu.main_menu.OnKeyboard = function (self, dik, keyboard_action)
	_G.main_menu_OnKeyboard(self, dik, keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED
			and dik == DIK_keys.DIK_F1 then
		ui_cheat_main.start_menu(self)
	end
	return true
end

local ss_ver = script_server_object_version()
_G.ver_prefix =	(ss_ver <= 7 and "soc")
				or ((ss_ver > 7 and ss_ver < 12) and "cs")
				or (ss_ver >= 12 and "cop")
if ver_prefix=="soc"
	and getFS():exist("$game_config$", "lost_alpha\\la_generic.ltx") then
		ver_prefix = "la" end

string.lower1 = function (str)
	return str and string.lower(str:gsub("([À-ß])",
		function(s) return string.char(s:byte()+32) end):gsub("¨", "¸"))
			or ""
end

math.normalize = function( n, min, max )
	if min > max then min, max = max, min end
	return (n>max and max) or (n<min and min) or n
end

_G.sys_ini = system_ini()

ini_file.r_clsid_ex = function (ini, section, line, def)
	if ini:section_exist(section) and ini:line_exist(section, line) then
		return ini:r_clsid(section, line)
	end
	return def
end
ini_file.r_bool_ex = function (ini, section, line, def)
	if ini:section_exist(section) and ini:line_exist(section, line) then
		return ini:r_bool(section, line)
	end
	return def
end
ini_file.r_float_ex = function (ini, section, line, def)
	if ini:section_exist(section) and ini:line_exist(section, line) then
		return ini:r_float(section, line)
	end
	return def
end
ini_file.r_string_ex = function (ini, section, line, def)
	if ini:section_exist(section) and ini:line_exist(section, line) then
		return ini:r_string(section, line)
	end
	return def
end
ini_file.r_u32_ex = function (ini, section, line, def)
	if ini:section_exist(section) and ini:line_exist(section, line) then
		return ini:r_u32(section, line)
	end
	return def
end
